version: '3'
services:

    haxe:
        restart: always
        build:
            context: ./haxe/
            dockerfile: dockerfile
        environment: 
            KEEP_CONTAINER_ALIVE: "yes"
        volumes:
            - ./shared:/docker-shared
            - ./haxe/scripts:/haxe
            - ../:/crapp-kit
        networks:
            - crapp-kit-network

    mysql:
        restart: always
        build:
            context: ./mysql/
            dockerfile: dockerfile
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: ""
        ports:
            - "3988:3306"
        networks:
            - crapp-kit-network

networks:
    crapp-kit-network:
