CREATE DATABASE IF NOT EXISTS `tests` DEFAULT CHARACTER SET = `utf8` /*!40100 DEFAULT CHARACTER SET utf8 */
;

CREATE TABLE tests.`my_table` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`unq` VARCHAR(128) NOT NULL,
	`name` VARCHAR(300) NOT NULL DEFAULT '',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `unq` (`unq`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB

;
